# Generated by Django 5.0.4 on 2024-05-12 14:34

import storage.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanbackend', '0002_alter_cart_id_alter_category_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=storage.custom_storage.AzureBlobStorage(), upload_to='products/'),
        ),
    ]
